update libs

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -14,18 +14,20 @@ ok() {
 
 _cleanup() {
 	docker-compose down --volumes --remove-orphans > /dev/null 2>&1
-	docker stop $(docker ps --all --quiet) > /dev/null 2>&1
-	docker rm $(docker ps --all --quiet --filter="status=exited") > /dev/null 2>&1
-	docker rmi $(docker images -f "dangling=true" -q) > /dev/null 2>&1
+	# docker rmi $(docker images --filter=reference='*:test' -q) > /dev/null 2>&1
 }
 
 trap '_cleanup; abort "Tests Failed For Unexpected Reasons"' HUP INT QUIT PIPE TERM SIGINT SIGTERM
 
-docker-compose up $1 test
+docker-compose -f docker-compose.dev.yml up $1 --force-recreate test
+if test $? -ne 0; then
+	abort "Docker Compose Failed"
+fi
+
 TEST_EXIT_CODE=`docker inspect test --format='{{.State.ExitCode}}'`
 
-test $TEST_EXIT_CODE -ne 0 && abort "Test FAIL" || ok "Test PASS"
-
 _cleanup
+
+test $TEST_EXIT_CODE -ne 0 && abort "Test FAIL" || ok "Test PASS"
 
 exit $TEST_EXIT_CODE
